---
# tasks file for php

- name: install php5-mysql
  apt: pkg=php5-mysql state=present

- name: Enable modules
  apache2_module: name={{ item }} state=present
  with_items:
     - php5

- name: Restart apache2 
  service: name=apache2 state=restarted

